eventplanner/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('events.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'events'

urlpatterns = [
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^event/(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
  url(r'^contact/$', views.ContactView, name='contact'),
  url(r'^about/$', views.AboutView, name='about'),
]

events/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class DefaultEvent(models.Model):
    event_category = models.CharField(max_length=250)
    event_description = models.CharField(max_length=500)
    event_image = models.FileField()

    def __str__(self):
        return self.event_description

class Event(models.Model):
    default_event = models.ForeignKey(DefaultEvent, on_delete=models.CASCADE)
    event_category = models.CharField(max_length=250)
    event_description = models.CharField(max_length=500)
    event_image = models.FileField()
    event_class = models.CharField(max_length=15, default='non-active')

    def __str__(self):
        return self.event_description

events/views.py
from django.views import generic
from django.shortcuts import render
from .models import DefaultEvent

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'events/index.html'

    def get_queryset(self):
        return DefaultEvent.objects.all()

class DetailView(generic.DetailView):
    model = DefaultEvent
    template_name = 'events/detail.html'

def ContactView(request):
    return render(request, 'events/contact.html')

def AboutView(request):
    return render(request, 'events/about.html')

events/templates/events/about.html
{% extends 'events/base.html' %}
{% block title %}About{% endblock %}

{% block body %}
  <div class="container about-ptn">
    <div class="row">
      <div class="col-sm-offset-3 col-sm-6">
        <div class="thumbnail my-about">
          <h3 class="right">
          {% block about_title %}
            About Us
          {% endblock%}
          </h3>
          <br>
          <h5>
          {% block about_content %}
          PricioX professional is an organization that provides services in event planning, hair dressing and textile design.
          Priciox professional is full of enthusiasm, creativity and has an experience of over 15 years.
          Priciox spelicialise in european & afro-carribean hair such as ghana braids, didi, dreadlocks, single plaits, pick and drop, twisting and treatment of hair
          {% endblock %}
          </h5>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

events/templates/events/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}home{% endblock %}</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link href="https://fonts.googleapis.com/css?family=Cinzel" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'events/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </head>
    <body>
        <div class="navbar-wrapper">
            <div class="container">
      
              <nav class="navbar navbar-static-top">
                <div class="container">
                  <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand my-nav" href="{% url 'events:index' %}">pricioX</a>
                  </div>
                  <div id="topNavBar" class="navbar-collapse collapse pull-right">
                    <ul class="nav navbar-nav">
                      <li class="active">
                        <a class="my-nav" href="{% url 'events:index' %}">
                          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; Home
                        </a>
                      </li>
                      <li class="dropdown">
                        <a class="my-nav" href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gallery <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><a href="/event/1/">Event Planning</a></li>
                          <li><a href="/event/2/">Hair Dressing</a></li>
                          <li><a href="/event/3/">Textile Design</a></li>
                        </ul>
                      </li>
                      <li><a class="my-nav" href="{% url 'events:contact' %}"><span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span>&nbsp; Contact</a></li>
                      <li><a class="my-nav" href="{% url 'events:about' %}"><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>&nbsp; About</a></li>
                    </ul>
                  </div>
                </div>
              </nav>
      
            </div>
          </div>
        {% block body %}
        {% endblock %}
    </body>

</html>

events/templates/events/contact.html
{% extends 'events/about.html' %}
{% block title %}Contact{% endblock %}

{% block about_title %}
  Contact
{% endblock %}
{% block about_content %}
<strong>Phone Number:</strong> +447404250009, &nbsp; 01204776595<br>
<strong>Email:</strong> ansinian@gmail.com <br>
<strong>Website Developer Email:</strong> phemmzmcllroy@gmail.com
{% endblock %}

events/templates/events/detail.html
{% extends 'events/base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-12">
      <div class="col-sm-8">
        
        <div class="col-sm-offset-1 thumbnail detail-box">
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
              {% for event in defaultevent.event_set.all %}
              <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter }}" class="{{ event.event_class }}"></li>
              {% endfor %}
            </ol>
            
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                {% for event in defaultevent.event_set.all %}
                  {% if event.event_class == 'active' %}
                  <div class="item active">
                      <img class="d-block w-100 detail-img" src="{{ event.event_image.url }}" alt="{{ event.event_description }}">
                    <div class="carousel-caption">
                      {{ event.event_description }}
                    </div>
                  </div>
                  {% else %}
                  <div class="item">
                    <img class="d-block w-100 detail-img" src="{{ event.event_image.url }}" alt="{{ event.event_description }}">
                    <div class="carousel-caption">
                      {{ event.event_description }}
                    </div>
                  </div>
                  {% endif %}
                {% endfor %}
              </div>
              
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
            </div>
          
        </div>
    </div>
  </div>
</div>
{% endblock %}

events/templates/events/index.html
{% extends 'events/base.html' %}

{% block body %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-lg-12 my-section">
      {% for event in object_list %}
        <div class="col-sm-4 col-lg-4">
          <div class="thumbnail">
              <a href="{% url 'events:detail' event.id %}">
                  <img src="{{ event.event_image.url }}" class="img-responsive my-img-resp">
              </a>
              <div class="caption">
                  <h2>{{ event.event_category }}</h2>
                  <span>{{ event.event_description }}</span>
                  <br>
                  <!-- View Details -->
                  <a
                    href="{% url 'events:detail' event.id %}"
                    class="btn btn-warning btn-sm"
                    role="button"
                  >View Details</a>
              </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}